import {test,expect} from '@playwright/test';
const date=new Date('2026-09-27T00:00:00Z');
test.beforeEach(async({page})=>{await page.clock.setFixedTime(date);});
test('home gives a finite briefing and does not mark visits as read',async({page})=>{await page.goto('/');await expect(page.locator('h1')).toContainText('今日简报');expect(await page.evaluate(()=>localStorage.getItem('matrix-reader-v1'))).toBeNull();await page.locator('[data-range="week"]').click();await expect(page.locator('[data-feed-item]:visible').first()).toBeVisible();await page.locator('[data-complete]').click();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('matrix-reader-v1')!));expect(state.read.length).toBeGreaterThan(0);expect(state.follows).toEqual([]);expect(state.bookmarks).toEqual([]);});
test('follow and bookmark persist independently across pages',async({page})=>{await page.goto('/projects/claude-code/');await page.locator('[data-follow="project:claude-code"]').first().click();await page.locator('[data-bookmark="project:claude-code"]').click();await page.goto('/following/');await expect(page.locator('[data-follow-item="project:claude-code"]')).toBeVisible();await page.getByText('我的收藏',{exact:true}).click();await expect(page.locator('[data-saved-item="project:claude-code"]')).toBeVisible();const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('matrix-reader-v1')!));expect(state.read).toEqual([]);});
test('search spans records and highlights matched terms safely',async({page})=>{await page.goto('/search/');await page.locator('#universal-query').fill('MCP');await expect(page.locator('#search-results article').first()).toBeVisible();await expect(page.locator('#search-results mark').first()).toContainText(/MCP/i);});
test('frontier filter and insights tabs are functional',async({page})=>{await page.goto('/events/');await page.locator('#f-stage').selectOption('frontier');expect(await page.locator('.event-card:visible').count()).toBeGreaterThan(0);await expect(page.locator('.event-card:visible:not([data-stage="frontier"])')).toHaveCount(0);await page.goto('/insights/#topics');await expect(page.locator('#topics')).toBeVisible();await expect(page.locator('#trends')).toBeHidden();});
test('blocked storage and reduced motion preserve keyboard reading',async({page})=>{await page.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked')}}));await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/following/');await expect(page.locator('#reader-status')).toBeVisible();const summary=page.locator('details').first().locator('summary');await summary.focus();await page.keyboard.press('Enter');await expect(page.locator('details').first()).not.toHaveAttribute('open','');});
for(const width of [360,768,1440])for(const theme of ['light','dark'])test(`responsive ${width} ${theme}`,async({page})=>{await page.setViewportSize({width,height:1000});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));for(const url of ['/','/events/','/projects/claude-code/','/insights/','/following/','/sources/','/topics/open-weight-coding/','/daily/','/daily/2026-09-27/','/trends/archive/2026-09-27/','/about/','/search/','/projects/','/en/events/','/en/following/','/en/']){await page.goto(`${url}?theme=${theme}`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),url).toBe(true);}expect(errors).toEqual([]);});
import AxeBuilder from '@axe-core/playwright';
for(const theme of ['light','dark'])test(`accessible reading ${theme}`,async({page})=>{for(const route of ['/','/projects/claude-code/','/events/ev-20260818-05/','/sources/','/insights/','/insights/#radar','/trends/open-weight-agentic-coding-models-chinese-labs/','/following/','/topics/open-weight-coding/','/daily/','/daily/2026-09-27/','/trends/archive/2026-09-27/','/about/','/search/']){const url=new URL(route,'http://127.0.0.1:4321');url.searchParams.set('theme',theme);await page.goto(url.pathname+url.search+url.hash);const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(report.violations,route).toEqual([]);}});
test('invalid import preserves data and valid import merges collections',async({page})=>{await page.goto('/following/');await page.locator('[data-follow="scenario:agents"]').click();await page.getByText('阅读数据管理',{exact:true}).click();await page.locator('#import-reader').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await expect(page.locator('#reader-status')).toContainText('导入失败');await page.locator('#import-reader').setInputFiles({name:'reading.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,follows:['project:claude-code'],bookmarks:['event:ev-20260925-01'],read:[],completed_version:null}))});await expect(page.locator('#reader-status')).toContainText('已合并');const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('matrix-reader-v1')!));expect(state.follows).toEqual(expect.arrayContaining(['scenario:agents','project:claude-code']));});

test('following retains a distinct global section and explains scenario matches',async({page})=>{await page.goto('/following/');await expect(page.locator('.global-feed-items')).toBeVisible();await page.locator('[data-follow="scenario:models"]').click();await expect(page.locator('.feed-items .feed-reason').filter({hasText:'模型选型'}).first()).toBeVisible();});

test('mobile navigation and theme controls remain visible in both languages',async({page})=>{await page.setViewportSize({width:360,height:900});for(const route of ['/','/en/','/events/','/en/events/']){await page.goto(route+'?theme=light');for(const link of await page.locator('.main-nav>a,.nav-utils>a,.theme-toggle').all()){const box=await link.boundingBox();expect(box).not.toBeNull();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(360);}await page.locator('#theme-toggle').click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');}});

test('home opens on the latest briefing even on a day without new changes',async({page})=>{await page.clock.setFixedTime(new Date('2026-10-15T00:00:00Z'));await page.goto('/');await expect(page.locator('[data-range="latest"]')).toHaveAttribute('aria-pressed','true');await expect(page.locator('[data-feed-item]:visible').first()).toBeVisible();await expect(page.locator('.feed-empty')).toBeHidden();await page.locator('[data-range="today"]').click();await expect(page.locator('.feed-empty')).toBeVisible();});
test('updates lead with what changed and keep the original story as context',async({page})=>{await page.goto('/?range=week');const update=page.locator('[data-feed-item]:visible',{has:page.locator('.brief-parent:visible')}).first();await expect(update).toBeVisible();const headline=(await update.locator('h2 a').textContent())!.trim();const original=(await update.locator('.brief-parent a').textContent())!.trim();expect(headline).not.toBe(original);await expect(update.locator('.brief-parent')).toContainText('原事件');});
test('RSS feeds are discoverable from every page and from project pages',async({page,request})=>{await page.goto('/projects/claude-code/');await expect(page.locator('link[rel="alternate"][type="application/rss+xml"]')).toHaveAttribute('href',/\/feed\.xml$/);const link=page.locator('a[href$="/feeds/projects/claude-code.xml"]');await expect(link).toBeVisible();const res=await request.get('/feeds/projects/claude-code.xml');expect(res.ok()).toBe(true);expect(await res.text()).toContain('<rss version="2.0"');});
test('feed cards state the rating and the next step',async({page})=>{await page.goto('/');const card=page.locator('[data-feed-item]:visible',{has:page.locator('.brief-action')}).first();await expect(card.locator('.brief-tier .badge')).toHaveText(/ADOPT|TRIAL|WATCH|IGNORE/);await expect(card.locator('.brief-action')).toContainText('建议动作');});
test('projects show their own judgment rather than an inherited event rating',async({page})=>{await page.goto('/projects/');const kimi=page.locator('.project-tile',{has:page.locator('a[href$="/projects/kimi/"]')});await expect(kimi.locator('.badge')).toHaveText('WATCH');await page.goto('/projects/claude-code/');await expect(page.locator('h1 .badge')).toHaveText('ADOPT');await expect(page.locator('.judgment-meta').first()).toContainText('判断复核于');await expect(page.locator('.timeline article')).not.toHaveCount(0);await expect(page.locator('.timeline .timeline-kind',{hasText:'重要更新'}).first()).toBeVisible();});
